version: '3.5'

services:
  client-api:
    image: clientinventory.api
    container_name: client-api
    depends_on: 
      - client-mongo
    ports:
      - "80:80"
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      client-nw:
  client-mongo:
    image: mongo
    container_name: client-mongo
    ports:
      - "27017:27017"
    networks: 
      client-nw:
networks:
  client-nw:
    name: client-nw